spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQLHOST}:${POSTGRESQLPORT}/${POSTGRESQLDATABASE}
    username: ${POSTGRESQLUSER}
    password: ${POSTGRESQLPASSWORD}
    name: asianfood

  sql:
    init:
      mode: always