spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQLHOST}/${POSTGRESQLDATABASE}
    username: ${POSTGRESQLUSER}
    password: ${POSTGRESQLPASSWORD}
    name: asianfood

  sql:
    init:
      mode: always

app:
  http:
    frontend:
      url: ${FRONTENDURL}