version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: asianfood
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /initial/init.sql
    ports:
      - 5432:5432